### ISSUE TITLE
Python3 Compatiblity again

### ISSUE THREAD

**Issue by SpaceTeddy** [motoz/nbetest#5]
Dear motoz,

seems that I get in trouble after updating python to >3.5 .
May you please recheck the "set" commands?
I get always the following failure:
```
Traceback (most recent call last):
  File "/Users/Christian/Documents/development/Aduro/nbetest_v13_rpi_test/client.py", line 249, in <module>
    args.func(args, proxy)
  File "/Users/Christian/Documents/development/Aduro/nbetest_v13_rpi_test/client.py", line 53, in setfunc
    l = proxy.set(args.path, args.value)
  File "/Users/Christian/Documents/development/Aduro/nbetest_v13_rpi_test/protocol.py", line 168, in set
    response = self.make_request(2, '.'.join(d[1:3]) + '=' + value, encrypt=True)
  File "/Users/Christian/Documents/development/Aduro/nbetest_v13_rpi_test/protocol.py", line 188, in make_request
    self.s.sendto(self.request.encode(), self.addr)
  File "/Users/Christian/Documents/development/Aduro/nbetest_v13_rpi_test/frames.py", line 82, in encode
    h += pad
TypeError: can't concat str to bytes
```

**Comment by motoz** [comment]
I did some quick fixes, seems to work now (with python 3.8.5). Didn't test if python 2 still works though...

**Comment by SpaceTeddy** [comment]
jap, works with python 3.9 now. Great! :)
Unfortunately I does not work with python 2.7 any more, but this version is outdated anyway. 
Hope it is ok for you to stay with python 3 only.

kr,
Chris

**Comment by motoz** [comment]
Yeah, it's not like I use this test program for anything anymore anyway. But as long as someone finds it useful I can at least try to keep it going.
